apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
data:
  # kafka
  {{ if .Values.kafka.enabled }}
  "CLUSTER_API_KEY": "{{ .Values.kafka.cluster_api_key }}"
  "CLUSTER_API_SECRET": "{{ .Values.kafka.cluster_api_secret }}"
  {{ end }}

  # RabbitMq
  {{ if .Values.rabbitmq.enabled }}
  "RABBIT_USERNAME": "{{ .Values.rabbitmq.username }}"
  "RABBIT_PASSWORD": "{{ .Values.rabbitmq.password }}"
  {{ end }}